var UNUSABLE_IMAGES = [
   "Image:Inaccurate1_469.gif",
   "Image:Spotlightnes3_241.png",
   "Image:Info_317.png",
   "Image:Barnstar.png",
   "Image:LinkFA star.jpg",
   "Image:Barnstar_of_Humour3_910.png",
   "Image:WikiDefender_Barnstar_353.png",
   "Image:Barnstar camera_91.png",
   "Image:Stop hand_731.png",
   "Image:ProtoClarity.png",
   "Image:Template icon Needs editing_501.gif",
   "Image:Template icon Needs editing_501.gif",
   "Image:197px Copyright.svg.png",
   "Image:Heckert_GNU_white_975.png",
   "Image:FA candidate alpha.png",
   "Image:Needs formatting_451.gif",
   "Image:ATTENTION4.gif",
   "Image:TITLE6.png",
   "Image:InUseClock.png",
   "Image:30px Apple_logo.gif",
   "Image:Laptopnigeria.jpg",
   "Image:Merge_590.png",
   "Image:Inaccurate2.gif",
   "Image:Page discussion_71.gif",
   "Image:Photoround.png",
   "Image:Magglass_326.png",
   "Image:Furcongrat.png",
   "Image:141123835_cf8cafd149.jpg",
   "Image:Stop hand_731.png",
   "Image:ProtoSplit.png",
   "Image:Spotlightnes3_241.png",
   "Image:Incomplete_856.gif",
   "Image:172665796_c35bd3fbbe.jpg",
   "Image:140030475_c8bd9744f2.jpg",
   "Image:44771952_9b0223c408.jpg",
   "Image:251140793_165d14e568.jpg",
   "Image:Smile Face 180.jpg",
   "Image:ProtoTitle.png",
   "Image:AwardTeamStarUIB.png",
   "Image:Dimanche_826.PNG",
   "Image:GMTm5.png",
   "Image:Crystal_email_474.png",
   "Image:120px Flag_of_Australia.svg.png",
   "Image:120px Flag_of_the_United_Kingdom.svg.png",
   "Image:120px Flag_of_the_United_States.svg.png",
   "Image:Firefoxlogo.png",
   "Image:Face grin expert 8573.png",
   "Image:IELogo.png",
   "Image:Tux..png",
   "Image:MacLogo_508.png",
   "Image:Facesmilebig.png",
   "Image:GMTm7.png",
   "Image:GMTm8.png",
   "Image:Exquisite kfind_376.png",
   "Image:SAC6.png",
   "Image:Face monkey_215.png",
   "Image:UserAK.gif",
   "Image:UserAL.gif",
   "Image:UserAZ.gif",
   "Image:WikiAdminUIB.png",
   "Image:Microsoft logo.png",
   "Image:IconDude.png",
   "Image:24872178_1365e66ee6.jpg",
   "Image:48840696_fd62f17b25.jpg",
   "Image:182633915_1131e22a03.jpg",
   "Image:JWM.gif",
   "Image:JWM.gif",
   "Image:Welcome_mat.jpg",
   "Image:Boat.jpg",
   "Image:Welcome_neon.jpg",
   "Image:Welcome_mat.jpg"
];
